import Head from "next/head";
import {Card} from "~/components/Card";
import {Card as CardModel} from "~/models";

const cards:CardModel[]  = [
  {
    color: 'blue',
    title: 'Получите\nпартнерскую ссылку',
    hasArrow: true,
    hero: 'hero-1.svg'
  },
  {
    color: 'purple',
    title: 'Расскажите\nо IIII.COM',
    hasArrow: true,
    hero: 'hero-2.svg'
  },
  {
    color: 'green',
    title: 'Получайте хороший процент\nот покупок по вашей ссылке!',
    hasArrow: false,
    hero: 'hero-3.svg'
  }
]

export default function Home() {
  return (
    <>
      <Head>
        <title>Frontend test task</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='container'>
        <div className="border">
          {cards.map((card, index) => (
              <Card card={card} key={index} index={index} />
          ))}
        </div>
      </div>
    </>
  );
}
